### ISSUE TITLE
我遇到一个语法错误

### ISSUE THREAD

**Issue by pangg11** [RunpuWei/Auto-Report#1]
![image](https://user-images.githubusercontent.com/48109998/158770995-13001368-cf9a-47d6-8466-8ac64e6dc80e.png)

**Comment by RunpuWei** [comment]
你是不是没有加USERS变量呀😂😂

**Comment by RunpuWei** [comment]
记得把USERS和SERVER_KEY环境变量写一下，和原项目一样的、

**Comment by pangg11** [comment]
我添加了USERS和SERVER_KEY环境变量。重复试了多次，都无效。
最终删掉仓库，重新Fork，然后就能用了。USERS和SERVER_KEY的值和之前一模一样的。

**Comment by pangg11** [comment]
晨午晚检分别几点打卡啊？

**Comment by RunpuWei** [comment]
打卡时间自己改cron设置就行，我默认设的 "*/30 */4 * * *"，就是每四个小时里每半小时打一次卡。0:00、0:30、4:00、4:30、8:00、8:30....... 具体你也可以改

**Comment by RunpuWei** [comment]
我刚又push了一下，把server酱换成wecom酱了，那个server酱不花钱看不见信息o(╥﹏╥)o

**Comment by pangg11** [comment]
![image](https://user-images.githubusercontent.com/48109998/158785783-600ea781-c09f-479b-bbd6-e85bd6224f6e.png)
咋定位到德州啦？

**Comment by RunpuWei** [comment]
默认地址我写的德州、、因为是一个德州同学给我的json文件   你改成用上次打卡数据或者改成你自己的默认数据就行了、、

**Comment by pangg11** [comment]
咋使用上次数据？

**Comment by RunpuWei** [comment]
![Uploading 4DB952AE-F2AE-4E8B-ADA7-10DF615D6E42.jpeg…]()

**Comment by RunpuWei** [comment]
![FF3E12C7-5E31-49DD-A96D-6C2EA203A6D3](https://user-images.githubusercontent.com/36250999/158789501-2596edd3-cf0c-43d7-8703-38f4c6b15f0a.jpeg)

**Comment by pangg11** [comment]
改好了，导员说不通报我，哈哈

**Comment by RunpuWei** [comment]
我刚刚把默认配置改成北邮西土城校区了，你可以重新fork一下、、（而且其实导员一般只看打没打卡，不看在哪打哈哈

**Comment by RunpuWei** [comment]
dbq。。。刚刚才发现打卡一直都是山东是个BUG，现在应该修好了呜呜
