### ISSUE TITLE
WEcom有bug

### ISSUE THREAD

**Issue by pangg11** [RunpuWei/Auto-Report#2]

**Comment by pangg11** [comment]
![image](https://user-images.githubusercontent.com/48109998/158807537-35627db8-67f1-42b6-9369-c908f7721476.png)

**Comment by RunpuWei** [comment]
还是一样，你没建WECOM环境变量（SECRET），你看你那里都是空的

**Comment by RunpuWei** [comment]
看readme说明，不是server key了，现在是wecom，然后输入的东西和原先也不一样

**Comment by pangg11** [comment]
不用wecom行吗
![image](https://user-images.githubusercontent.com/48109998/158810985-c953fb53-d994-43fe-86ae-7851ea5cccd9.png)

**Comment by RunpuWei** [comment]
格式。。。都要写成字符串呀WECOM=("123", "123", "wxid4451512") 要加引号的宝贝

**Comment by RunpuWei** [comment]
今晚最后看了一下，丢了个字段，又修了一下，现在应该彻底没问题了，麻烦重新fork一下吧（绝对是最后一次！！）😂😂😂
